---
# Role: usegalaxy_eu.handy.os_setup
enable_hostname: true
enable_powertools: true
enable_remap_user: true
enable_exclude_packages: true
enable_pam_limits: true
enable_install_software: true
enable_create_user: true
software_groups_to_install:
  - admin
  - debug
  - editors
  - terminals
  - utils
handy_users:
  - user_name: '{{ galaxy_user.name }}'
    user_uid: '{{ galaxy_user.uid }}'
    user_group: '{{ galaxy_group.name }}'
    user_comment: 'Galaxy useraccount'
    user_create_home: '{{ galaxy_user.create_home }}'
    user_home: '{{ galaxy_user.home }}'
    user_shell: '{{ galaxy_user.shell }}'
handy_groups:
  - group_name: '{{ galaxy_group.name }}'
    group_gid: '{{ galaxy_group.gid }}'

# Role: galaxyproject.miniconda
conda_prefix_dir: '/opt/miniconda'
miniconda_prefix: '{{ conda_prefix_dir }}'
galaxy_conda_create_env: true
galaxy_conda_env_packages:
  - python=3.11
  - pip

# Certbot
certbot_virtualenv_package_name: python3-virtualenv
certbot_dns_provider: route53
certbot_auth_method: --standalone
certbot_domains: "{{ server_names }}"
certbot_post_renewal: |
  systemctl restart nginx || true
certbot_share_key_users:
  - nginx

# AWS Credentials for certbot-route53
aws_cli_credentials:
  - access_key: "{{ aws_credentials.certbot.AWS_ACCESS_KEY }}"
    secret_key: "{{ aws_credentials.certbot.AWS_SECRET_KEY }}"
    homedir: /root
    owner: root
    group: root

# Role: usegalaxy-eu.nginx
nginx_selinux_allow_local_connections: true
nginx_servers:
  - redirect-ssl
nginx_ssl_servers:
  - tpv-broker
nginx_enable_default_server: false
nginx_flavor: ''

# Nginx Letsencrypt bindings
nginx_ssl_role: usegalaxy-eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/user/privkey-nginx.pem

# Role: usegalaxy_eu.ansible_tpv_broker
tpv_broker_dir: '/opt/tpv-broker'
tpv_broker_repo: 'https://github.com/usegalaxy-eu/tpv-broker.git'
tpv_broker_commit_id: 'main'
tpv_broker_force_checkout: true # discards local changes if any
tpv_broker_venv_dir: '/opt/tpv-broker/venv'
tpv_broker_virtualenv_command: '{{ conda_prefix_dir }}/envs/_galaxy_/bin/python -m venv --copies'
tpv_broker_systemd_service_name: 'tpv-broker'
tpv_broker_systemd_service_user: 'nginx'
tpv_broker_ssl_certificate: '{{ nginx_conf_ssl_certificate }}'
tpv_broker_ssl_certificate_key: '{{ nginx_conf_ssl_certificate_key }}'
tpv_broker_nginx_conf: true
tpv_broker_proxy_config:
  location: '/'
  proxy_pass_host: '127.0.0.1'
  proxy_pass_port: 8000
  proxy_pass_protocol: 'https'
influx_address: '{{ influxdb.host }}'
influx_port: 8086
influx_db: '{{ influxdb.node.database }}'
influx_username: '{{ influxdb.node.username }}'
influx_password: '{{ influxdb.node.password }}'
