---
dnbd3_is_proxy: false
dnbd3_base_path: "/export/dnbd3-cache/images"
tftpboot_path: "/export/dnbd3-cache/boot"
apache_listen_port: 80
apache_vhosts:
  - servername: "example.com"
    documentroot: "/export/dnbd3-cache/http"
