---
# This file is used to define custom messages for tools that are displayed in the tool form
# The toolmsg webhook wil be triggered and the message will be displayed in the tool form if the tool_id matches

# Format:
# toolmsg_messages:
#   - tool_id: to match subject.startsWith(tool_id)
#              Best to use remove version numbers and trailing slash
#              e.g. toolshed.g2.bx.psu.edu/repos/galaxyp/diann/diann
#     message: A custom HTML message to be displayed for this tool
#     class: bootstrap class [primary, info, success, warning, danger]

# Example 1: Display a warning message for the tool ncbi_blastp_wrapper, the message will be in bold format
# toolmsg_messages:
#   - tool_id: toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_blastp_wrapper
#     message: <strong>We recommend using Diamond instead.</strong>
#     class: warning

toolmsg_messages:
  - tool_id: toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_blastp_wrapper
    message: >
      <strong>We recommend using
      <a href="https://usegalaxy.eu/?tool_id=bg_diamond">Diamond</a>
      instead. Pairwise alignment of proteins and translated DNA can be up to 100x-10,000x faster than BLAST.</strong>
    class: warning

toolmsg_messages:
  - tool_id: toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc
    message: >
      <strong>We recommend using
      <a href="https://usegalaxy.eu/?tool_id=falco">Falco</a>
      instead. Falco is 3 times faster and offers the same functionality as FASTQC.</strong>
    class: warning
