http:
  routers:
    influxdb-rtr:
      rule: "Host(`influxdb.galaxyproject.eu`)"
      service: influxdb
      entryPoints:
        - websecure
      tls:
        certResolver: "route53"
        domains:
          - main: "influxdb.galaxyproject.eu"
