http:
  routers:
    usegalaxy-eu-rtr:
      rule: "Host(`usegalaxy.eu`) || HostRegexp(`^.+\\.usegalaxy\\.eu`)"
      service: "usegalaxy-eu"
      entryPoints:
        - websecure
      tls:
        certResolver: "route53"
        domains:
          - main: "usegalaxy.eu"
            sans:
              - "*.ep.interactivetool.usegalaxy.eu"
